# GitWhisper `init` command (PowerShell).
# Creates .gitwhisperconfig and installs the smart git hooks.

function New-GwConfigFile {
    $content = @'
# GitWhisper configuration
# Created by `gitwhisper init`. Re-run `gitwhisper init` to update hooks after edits.

[general]
# include emoji in generated commit messages (true/false)
emoji = true

# suggestion pre-filled by the hook: 1=simple+emoji, 2=simple, 3=detailed+emoji, 4=detailed
default = 1

# maintainers excluded from the "community contributors" section of the changelog
core_maintainers =

[hooks]
# pre-fill the commit message on `git commit` (true/false)
prepare = true

# reject commits that do not follow Conventional Commits (true/false)
validate = true
'@
    $content | Out-File -FilePath ".gitwhisperconfig" -Encoding UTF8
    Write-Host "  Created .gitwhisperconfig" -ForegroundColor Green
}

function Get-GitwhisperCommand {
    $script = Join-Path $script:GW_SCRIPT_ROOT "gitwhisper.ps1"
    if (Test-Path $script) {
        return "powershell.exe -NoProfile -ExecutionPolicy Bypass -File '$($script.Replace('\', '/'))'"
    }
    return "gitwhisper"
}

function Get-PrepareHookContent {
    param([string]$Cmd)

    $tpl = @'
#!/bin/sh
# Generated by GitWhisper init. Re-run `gitwhisper init` to update.
GW_CMD="__GW_CMD__"

MSG_FILE="$1"
SOURCE="$2"

# only pre-fill plain commits (skip -m, --amend, merge, template, etc.)
case "$SOURCE" in
    message|template|merge|squash|commit) exit 0 ;;
esac

# do nothing when there are no staged changes
if ! git diff --cached --quiet 2>/dev/null; then
    SUGGEST=$(eval "$GW_CMD suggest < /dev/null" 2>/dev/null)
    if [ -n "$SUGGEST" ]; then
        # only pre-fill when the message file has no real content yet
        REAL=$(grep -v '^#' "$MSG_FILE" | grep -v '^[[:space:]]*$' | head -1)
        if [ -z "$REAL" ]; then
            printf '%s\n' "$SUGGEST" > "$MSG_FILE"
        fi
    fi
fi

exit 0
'@
    return $tpl.Replace("__GW_CMD__", $Cmd)
}

function Get-CommitMsgHookContent {
    $tpl = @'
#!/bin/sh
# Generated by GitWhisper init. Re-run `gitwhisper init` to update.
MSG_FILE="$1"

FIRST_LINE=""
while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
        \#*) continue ;;
        "") continue ;;
    esac
    FIRST_LINE="$line"
    break
done < "$MSG_FILE"

if ! echo "$FIRST_LINE" | grep -qE '^[^[:alnum:]]*(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert|db)(\([^)]*\))?(!)?: .+'; then
    echo ""
    echo "GitWhisper: commit message does not follow Conventional Commits."
    echo ""
    echo "  Expected: <type>(<scope>): <description>"
    echo "  Example:  feat(api): add login endpoint"
    echo ""
    echo "  Run 'gitwhisper' to generate a message, or edit the subject line."
    echo ""
    exit 1
fi

exit 0
'@
    return $tpl
}

function Install-Hook {
    param(
        [string]$Path,
        [string]$Content,
        [switch]$Force
    )

    if (Test-Path $Path) {
        $existing = Get-Content $Path -Raw -ErrorAction SilentlyContinue
        if ($existing -and $existing -notmatch "GitWhisper") {
            if (-not $Force) {
                Write-Host ""
                $answer = Read-Host "  $(Split-Path $Path -Leaf) exists and is not from GitWhisper. Back up and overwrite? (y/n)"
                if ($answer -ne "y" -and $answer -ne "Y") {
                    Write-Host "  Skipping $(Split-Path $Path -Leaf)." -ForegroundColor Yellow
                    return
                }
            }
            Copy-Item $Path "$Path.bak" -Force
            Write-Host "  Backed up existing hook to $Path.bak" -ForegroundColor Yellow
        }
    }
    $Content | Out-File -FilePath $Path -Encoding ASCII -NoNewline
    Write-Host "  Installed $(Split-Path $Path -Leaf)" -ForegroundColor Green
}

function Invoke-Init {
    param([switch]$Force)

    Write-Host ""
    Write-Host "=== GitWhisper init ===" -ForegroundColor Cyan
    Write-Host ""

    if (Test-Path ".gitwhisperconfig") {
        if ($Force) {
            Write-Host "  .gitwhisperconfig already exists. Recreating." -ForegroundColor Yellow
            New-GwConfigFile
        } else {
            Write-Host "  .gitwhisperconfig already exists. Keeping it." -ForegroundColor Green
        }
    } else {
        New-GwConfigFile
    }

    $hooksDir = Join-Path ".git" "hooks"
    if (-not (Test-Path $hooksDir)) {
        Write-Host ""
        Write-Host "  Error: could not find $hooksDir." -ForegroundColor Red
        exit 1
    }

    $gwCmd = Get-GitwhisperCommand

    if ($gwConfig["hooks.prepare"] -eq "false") {
        Remove-Item (Join-Path $hooksDir "prepare-commit-msg") -Force -ErrorAction SilentlyContinue
        Write-Host "  prepare-commit-msg disabled in config. Removed." -ForegroundColor Yellow
    } else {
        Install-Hook -Path (Join-Path $hooksDir "prepare-commit-msg") -Content (Get-PrepareHookContent -Cmd $gwCmd) -Force:$Force
    }

    if ($gwConfig["hooks.validate"] -eq "false") {
        Remove-Item (Join-Path $hooksDir "commit-msg") -Force -ErrorAction SilentlyContinue
        Write-Host "  commit-msg disabled in config. Removed." -ForegroundColor Yellow
    } else {
        Install-Hook -Path (Join-Path $hooksDir "commit-msg") -Content (Get-CommitMsgHookContent) -Force:$Force
    }

    Write-Host ""
    Write-Host "  Done! GitWhisper hooks installed." -ForegroundColor Green
    Write-Host "  Next 'git commit' will pre-fill a suggested message." -ForegroundColor White
    Write-Host "  Config file: .gitwhisperconfig" -ForegroundColor White
    Write-Host ""
}
