# GitWhisper `init` command (Bash).
# Creates .gitwhisperconfig and installs the smart git hooks.

new_gw_config_file() {
    cat > .gitwhisperconfig <<'EOF'
# GitWhisper configuration
# Created by `gitwhisper init`. Re-run `gitwhisper init` to update hooks after edits.

[general]
# include emoji in generated commit messages (true/false)
emoji = true

# suggestion pre-filled by the hook: 1=simple+emoji, 2=simple, 3=detailed+emoji, 4=detailed
default = 1

# maintainers excluded from the "community contributors" section of the changelog
core_maintainers =

[hooks]
# pre-fill the commit message on `git commit` (true/false)
prepare = true

# reject commits that do not follow Conventional Commits (true/false)
validate = true
EOF
    echo -e "  \033[32mCreated .gitwhisperconfig\033[0m"
}

get_gitwhisper_command() {
    if [[ "$0" == */* ]]; then
        local abs
        abs=$(cd "$(dirname "$0")" && pwd)
        echo "bash '$abs/$(basename "$0")'"
    else
        echo "gitwhisper"
    fi
}

get_prepare_hook_content() {
    local cmd="$1"
    cat <<EOF
#!/bin/sh
# Generated by GitWhisper init. Re-run \`gitwhisper init\` to update.
GW_CMD="$cmd"

MSG_FILE="\$1"
SOURCE="\$2"

# only pre-fill plain commits (skip -m, --amend, merge, template, etc.)
case "\$SOURCE" in
    message|template|merge|squash|commit) exit 0 ;;
esac

# do nothing when there are no staged changes
if ! git diff --cached --quiet 2>/dev/null; then
    SUGGEST=\$(eval "\$GW_CMD suggest < /dev/null" 2>/dev/null)
    if [ -n "\$SUGGEST" ]; then
        # only pre-fill when the message file has no real content yet
        REAL=\$(grep -v '^#' "\$MSG_FILE" | grep -v '^[[:space:]]*\$' | head -1)
        if [ -z "\$REAL" ]; then
            printf '%s\n' "\$SUGGEST" > "\$MSG_FILE"
        fi
    fi
fi

exit 0
EOF
}

get_commit_msg_hook_content() {
    cat <<'EOF'
#!/bin/sh
# Generated by GitWhisper init. Re-run `gitwhisper init` to update.
MSG_FILE="$1"

FIRST_LINE=""
while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
        \#*) continue ;;
        "") continue ;;
    esac
    FIRST_LINE="$line"
    break
done < "$MSG_FILE"

if ! echo "$FIRST_LINE" | grep -qE '^[^[:alnum:]]*(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert|db)(\([^)]*\))?(!)?: .+'; then
    echo ""
    echo "GitWhisper: commit message does not follow Conventional Commits."
    echo ""
    echo "  Expected: <type>(<scope>): <description>"
    echo "  Example:  feat(api): add login endpoint"
    echo ""
    echo "  Run 'gitwhisper' to generate a message, or edit the subject line."
    echo ""
    exit 1
fi

exit 0
EOF
}

install_hook() {
    local path="$1" content="$2" force="${3:-0}"

    if [[ -f "$path" ]]; then
        local existing
        existing=$(cat "$path" 2>/dev/null)
        if [[ -n "$existing" && "$existing" != *"GitWhisper"* ]]; then
            if [[ "$force" != "1" ]]; then
                echo ""
                read -p "  $(basename "$path") exists and is not from GitWhisper. Back up and overwrite? (y/n): " answer
                if [[ "$answer" != "y" && "$answer" != "Y" ]]; then
                    echo -e "  \033[33mSkipping $(basename "$path").\033[0m"
                    return
                fi
            fi
            cp "$path" "$path.bak"
            echo -e "  \033[33mBacked up existing hook to $path.bak\033[0m"
        fi
    fi
    printf '%s\n' "$content" > "$path"
    echo -e "  \033[32mInstalled $(basename "$path")\033[0m"
}

invoke_init() {
    local force=false
    for a in "$@"; do
        [[ "$a" == "--force" || "$a" == "-Force" ]] && force=true
    done

    echo ""
    echo -e "\033[36m=== GitWhisper init ===\033[0m"
    echo ""

    if [[ -f ".gitwhisperconfig" ]]; then
        if [[ "$force" == true ]]; then
            echo -e "  \033[33m.gitwhisperconfig already exists. Recreating.\033[0m"
            new_gw_config_file
        else
            echo -e "  \033[32m.gitwhisperconfig already exists. Keeping it.\033[0m"
        fi
    else
        new_gw_config_file
    fi

    local hooks_dir=".git/hooks"
    if [[ ! -d "$hooks_dir" ]]; then
        echo ""
        echo -e "  \033[31mError: could not find $hooks_dir.\033[0m"
        exit 1
    fi

    local gw_cmd f=0
    gw_cmd=$(get_gitwhisper_command)
    [[ "$force" == true ]] && f=1

    if [[ "${GW_CONFIG[hooks.prepare]}" == "false" ]]; then
        rm -f "$hooks_dir/prepare-commit-msg"
        echo -e "  \033[33mprepare-commit-msg disabled in config. Removed.\033[0m"
    else
        install_hook "$hooks_dir/prepare-commit-msg" "$(get_prepare_hook_content "$gw_cmd")" "$f"
    fi

    if [[ "${GW_CONFIG[hooks.validate]}" == "false" ]]; then
        rm -f "$hooks_dir/commit-msg"
        echo -e "  \033[33mcommit-msg disabled in config. Removed.\033[0m"
    else
        install_hook "$hooks_dir/commit-msg" "$(get_commit_msg_hook_content)" "$f"
    fi

    echo ""
    echo -e "  \033[32mDone! GitWhisper hooks installed.\033[0m"
    echo -e "  Next 'git commit' will pre-fill a suggested message."
    echo -e "  Config file: .gitwhisperconfig"
    echo ""
}
