#!/usr/bin/env bash
# GitWhisper interactive installer for Bash / Zsh / Sh.
# Install once, use `gitwhisper` in any project.

set -euo pipefail

GW_VERSION="0.4.0"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GW_SCRIPT="$SCRIPT_DIR/gitwhisper.sh"
GW_INSTALL_DIR="$HOME/.gitwhisper"
MARKER_START="# >>> GitWhisper >>>"
MARKER_END="# <<< GitWhisper <<<"

C_RESET='\033[0m'
C_BOLD='\033[1m'
C_DIM='\033[2m'
C_RED='\033[31m'
C_GREEN='\033[32m'
C_YELLOW='\033[33m'
C_CYAN='\033[36m'
C_MAGENTA='\033[35m'

say()  { echo -e "${C_BOLD}  ${C_CYAN}◆${C_RESET} $1"; }
ok()   { echo -e "${C_BOLD}  ${C_GREEN}✔${C_RESET} $1"; }
warn() { echo -e "${C_BOLD}  ${C_YELLOW}⚠${C_RESET} $1"; }
err()  { echo -e "${C_BOLD}  ${C_RED}✘${C_RESET} $1"; }

box_lines() {
    local max=0 line pad
    for line in "$@"; do
        [[ ${#line} -gt $max ]] && max=${#line}
    done
    local top="" bottom=""
    top=$(printf '─%.0s' $(seq 1 "$max"))
    echo -e "  ${C_CYAN}┌─${top}─┐${C_RESET}"
    for line in "$@"; do
        pad=$((max - ${#line}))
        echo -e "  ${C_CYAN}│${C_RESET} $line$(printf ' %.0s' $(seq 1 "$pad")) ${C_CYAN}│${C_RESET}"
    done
    echo -e "  ${C_CYAN}└─${top}─┘${C_RESET}"
}

banner() {
    box_lines \
        "GitWhisper Installer v$GW_VERSION" \
        "Conventional Commits + gitmoji, automatically." \
        ""
}

ask_yn() { # prompt default(y|n) -> echoes y|n
    local prompt="$1" default="${2:-}" ans hint=""
    [[ "$default" == "y" ]] && hint=" [Y/n]"
    [[ "$default" == "n" ]] && hint=" [y/N]"
    while true; do
        read -r -p "  $prompt$hint: " ans || { echo "$default"; return 0; }
        ans=$(echo "$ans" | tr '[:upper:]' '[:lower:]')
        [[ -z "$ans" ]] && ans="$default"
        case "$ans" in
            y|yes) echo "y"; return 0 ;;
            n|no)  echo "n"; return 0 ;;
        esac
    done
}

ask_number() { # prompt min max -> echoes number
    local prompt="$1" min="$2" max="$3" ans
    while true; do
        read -r -p "  $prompt ($min-$max): " ans || { echo "$min"; return 0; }
        if [[ "$ans" =~ ^[0-9]+$ ]] && (( ans >= min && ans <= max )); then
            echo "$ans"
            return 0
        fi
    done
}

ask_path() { # prompt default -> echoes path
    local prompt="$1" default="$2" ans
    read -r -p "  $prompt [$default]: " ans || ans="$default"
    [[ -z "$ans" ]] && ans="$default"
    ans="${ans/#\~/$HOME}"
    echo "$ans"
}

detect_shell() {
    if [[ -n "${ZSH_VERSION:-}" ]]; then echo "zsh"
    elif [[ -n "${BASH_VERSION:-}" ]]; then echo "bash"
    elif [[ -n "${FISH_VERSION:-}" ]]; then echo "fish"
    else echo "sh"; fi
}

default_profile() {
    case "$(detect_shell)" in
        zsh)  echo "${ZDOTDIR:-$HOME}/.zshrc" ;;
        bash) echo "$HOME/.bashrc" ;;
        fish) echo "$HOME/.config/fish/config.fish" ;;
        *)    echo "$HOME/.profile" ;;
    esac
}

ensure_profile() { # path -> creates parent dir + file
    local dir
    dir=$(dirname "$1")
    [[ -d "$dir" ]] || mkdir -p "$dir"
    [[ -f "$1" ]] || touch "$1"
}

already_installed() { grep -qF "$MARKER_START" "$1" 2>/dev/null; }

install_engine() {
    # Self-contained copy of the Python engine + thin wrappers.
    mkdir -p "$GW_INSTALL_DIR"
    cp -f "$SCRIPT_DIR/gitwhisper.sh" "$GW_INSTALL_DIR/gitwhisper.sh" 2>/dev/null || true
    cp -f "$SCRIPT_DIR/gitwhisper.ps1" "$GW_INSTALL_DIR/gitwhisper.ps1" 2>/dev/null || true
    rm -rf "$GW_INSTALL_DIR/python"
    if [ -d "$SCRIPT_DIR/python" ]; then
        cp -R "$SCRIPT_DIR/python" "$GW_INSTALL_DIR/python"
    fi
    chmod +x "$GW_INSTALL_DIR/gitwhisper.sh" 2>/dev/null || true
}

install_profile_function() { # profile
    install_engine
    cat >> "$1" <<EOF

$MARKER_START
gitwhisper() { bash "$GW_INSTALL_DIR/gitwhisper.sh" "\$@"; }
$MARKER_END
EOF
}

install_bin_wrapper() { # bindir profile
    install_engine
    mkdir -p "$1"
    cat > "$1/gitwhisper" <<EOF
#!/usr/bin/env bash
# Generated by the GitWhisper installer.
exec bash "$GW_INSTALL_DIR/gitwhisper.sh" "\$@"
EOF
    chmod +x "$1/gitwhisper"
    if ! echo "$PATH" | tr ':' '\n' | grep -qxF "$1"; then
        cat >> "$2" <<EOF

$MARKER_START
export PATH="$1:\$PATH"
$MARKER_END
EOF
    fi
}

remove_profile_block() { # file
    [[ -f "$1" ]] || return 0
    local tmp
    tmp=$(mktemp)
    awk -v s="$MARKER_START" -v e="$MARKER_END" '
        $0==s { skip=1; next }
        $0==e { skip=0; next }
        !skip { print }
    ' "$1" > "$tmp"
    mv "$tmp" "$1"
}

detect_bin_dir_from_profile() { # file -> echoes bin dir exported in the block
    sed -n 's|^export PATH="\([^"]*\):\$PATH"$|\1|p' "$1" 2>/dev/null | head -1
}

uninstall_all() { # profile [bindir]
    local profile="$1" bindir="${2:-}" from_prof d
    from_prof=$(detect_bin_dir_from_profile "$profile")
    remove_profile_block "$profile"
    for d in "$bindir" "$from_prof"; do
        if [[ -n "$d" && -x "$d/gitwhisper" ]]; then
            rm -f "$d/gitwhisper"
            ok "Removed $d/gitwhisper"
        fi
    done
    rm -f "$GW_INSTALL_DIR/gitwhisper.sh" "$GW_INSTALL_DIR/gitwhisper.ps1" 2>/dev/null || true
    rm -rf "$GW_INSTALL_DIR/python" 2>/dev/null || true
    ok "GitWhisper removed from $profile"
    warn "Restart your terminal or run: source $profile"
}

install_all() { # profile type bindir  (idempotent: replaces any previous block)
    ensure_profile "$1"
    remove_profile_block "$1"
    case "$2" in
        function)
            install_profile_function "$1"
            ;;
        bin)
            install_bin_wrapper "$3" "$1"
            ;;
    esac
}

print_status() { # profile integration bindir
    local shell
    shell=$(detect_shell)
    box_lines \
        "Status" \
        "  shell            : $shell" \
        "  profile file     : $1" \
        "  integration      : $2" \
        "  bin directory    : $3" \
        "  installed        : $(already_installed "$1" && echo yes || echo no)"
}

show_options() { # profile type bindir
    box_lines \
        "Install options" \
        "  [1] Shell profile    : $1" \
        "  [2] Integration      : $2  (1=function in profile, 2=executable in bin)" \
        "  [3] Bin directory    : $3"
}

edit_options() {
    local profile="$1" integration="$2" bindir="$3" t
    while true; do
        echo "" >&2
        show_options "$profile" "$integration" "$bindir" >&2
        echo "" >&2
        echo -e "  ${C_CYAN}[1-3]${C_RESET} edit an option   ${C_GREEN}[I]${C_RESET} install now   ${C_DIM}[Q]${C_RESET} back" >&2
        read -r -p "  Choose: " ans >&2 || { echo ""; return; }
        case "$ans" in
            1) profile=$(ask_path "Shell profile file" "$profile") ;;
            2) integration="function"
               t=$(ask_number "Integration (1=function in profile, 2=executable in bin)" 1 2)
               [[ "$t" == "2" ]] && integration="bin" ;;
            3) [[ "$integration" == "bin" ]] && bindir=$(ask_path "Bin directory" "$bindir") ;;
            i|I) echo "$profile|$integration|$bindir"; return ;;
            q|Q) echo ""; return ;;
        esac
    done
}

setup_project() {
    echo ""
    box_lines "Project setup" "Install GitWhisper hooks in a project"
    echo ""
    local dir="$PWD"
    read -r -p "  Project directory [$dir]: " d || d=""
    [[ -n "$d" ]] && dir="$d"
    dir="${dir/#\~/$HOME}"
    dir=$(cd "$dir" 2>/dev/null && pwd || echo "$dir")
    if [[ ! -d "$dir/.git" ]]; then
        warn "No .git directory found in $dir."
        if [[ "$(ask_yn "Continue anyway?" "n")" != "y" ]]; then
            return 1
        fi
    fi
    echo ""
    local emoji default prepare validate
    emoji=$(ask_yn "Include emoji in commit messages?" "y")
    default=$(ask_number "Default message format (1=simple+emoji, 2=simple, 3=detailed+emoji, 4=detailed)" 1 4)
    prepare=$(ask_yn "Enable pre-fill hook (prepare-commit-msg)?" "y")
    validate=$(ask_yn "Enforce Conventional Commits (commit-msg hook)?" "y")
    echo ""
    box_lines \
        "Project setup summary" \
        "  directory  : $dir" \
        "  emoji      : $emoji" \
        "  default    : $default" \
        "  pre-fill   : $prepare" \
        "  validate   : $validate"
    if [[ "$(ask_yn "Apply?" "y")" != "y" ]]; then
        return 1
    fi
    cat > "$dir/.gitwhisperconfig" <<EOF
# GitWhisper configuration
# Created by the GitWhisper installer.

[general]
emoji = $emoji
default = $default

[hooks]
prepare = $prepare
validate = $validate
EOF
    (cd "$dir" && bash "$GW_SCRIPT" init)
    ok "Project $dir is ready."
}

print_help() {
    banner
    echo -e "  ${C_BOLD}Usage:${C_RESET}"
    echo -e "    ./install.sh                 ${C_DIM}interactive wizard${C_RESET}"
    echo -e "    ./install.sh --check         ${C_DIM}show detection status${C_RESET}"
    echo -e "    ./install.sh --yes --profile ~/.bashrc [--type function|bin] [--bin-dir ~/.local/bin]"
    echo -e "                                ${C_DIM}non-interactive install${C_RESET}"
    echo -e "    ./install.sh --uninstall [--profile ~/.bashrc]"
    echo -e "                                ${C_DIM}remove GitWhisper${C_RESET}"
    echo ""
    echo -e "  ${C_BOLD}Flags:${C_RESET}"
    echo -e "    -h, --help        show this help"
    echo -e "    -c, --check       detect shell/profile and print status"
    echo -e "    -y, --yes         accept defaults, no prompts"
    echo -e "    -p, --profile     profile file to modify"
    echo -e "    -t, --type        integration: function (default) or bin"
    echo -e "    -b, --bin-dir     bin directory (only for --type bin)"
    echo -e "    -u, --uninstall   remove GitWhisper from the profile"
    echo ""
}

main() {
    local profile integration bindir
    profile=""
    integration="function"
    bindir="$HOME/.local/bin"
    local noninteractive=false do_uninstall=false do_check=false

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h|--help) print_help; return 0 ;;
            -c|--check) do_check=true; shift ;;
            -y|--yes) noninteractive=true; shift ;;
            -p|--profile) profile="$2"; shift 2 ;;
            -t|--type) integration="$2"; shift 2 ;;
            -b|--bin-dir) bindir="$2"; shift 2 ;;
            -u|--uninstall) do_uninstall=true; shift ;;
            *) err "Unknown option: $1"; print_help; return 1 ;;
        esac
    done

    [[ -z "$profile" ]] && profile=$(default_profile)
    case "$integration" in
        function|bin) ;;
        *) err "Invalid integration type: $integration (use function or bin)"; return 1 ;;
    esac

    if [[ ! -f "$GW_SCRIPT" ]]; then
        err "gitwhisper.sh not found next to this installer ($SCRIPT_DIR)."
        return 1
    fi

    INTEGRATION="$integration"

    if [[ "$do_check" == true ]]; then
        print_status "$profile" "$integration" "$bindir"
        return 0
    fi

    if [[ "$do_uninstall" == true ]]; then
        if [[ "$noninteractive" == true ]] || already_installed "$profile"; then
            uninstall_all "$profile" "$bindir"
            return 0
        fi
        err "GitWhisper is not installed in $profile."
        return 1
    fi

    if [[ "$noninteractive" == true ]]; then
        install_all "$profile" "$integration" "$bindir"
        print_status "$profile" "$integration" "$bindir"
        ok "GitWhisper installed."
        warn "Restart your terminal or run: source $profile"
        return 0
    fi

    banner
    while true; do
        echo ""
        print_status "$profile" "$integration" "$bindir"
        local installed
        installed=$(already_installed "$profile" && echo yes || echo no)
        echo ""
        if [[ "$installed" == "yes" ]]; then
            echo -e "  ${C_GREEN}GitWhisper is installed.${C_RESET}"
        fi
        echo ""
        if [[ "$installed" == "yes" ]]; then
            echo -e "  ${C_CYAN}1)${C_RESET} Reinstall / update"
        else
            echo -e "  ${C_CYAN}1)${C_RESET} Install now"
        fi
        echo -e "  ${C_CYAN}2)${C_RESET} Change install options"
        echo -e "  ${C_CYAN}3)${C_RESET} Set up a project (hooks + config)"
        echo -e "  ${C_CYAN}4)${C_RESET} Uninstall"
        echo -e "  ${C_CYAN}5)${C_RESET} Quit"
        echo ""
        read -r -p "  Choose [1-5]: " ans || ans="5"
        case "$ans" in
            1)
                install_all "$profile" "$integration" "$bindir"
                echo ""
                print_status "$profile" "$integration" "$bindir"
                ok "GitWhisper installed."
                warn "Restart your terminal or run: source $profile"
                ;;
            2)
                local edited
                edited=$(edit_options "$profile" "$integration" "$bindir")
                [[ -z "$edited" ]] && continue
                profile=$(echo "$edited" | cut -d'|' -f1)
                integration=$(echo "$edited" | cut -d'|' -f2)
                bindir=$(echo "$edited" | cut -d'|' -f3)
                install_all "$profile" "$integration" "$bindir"
                echo ""
                print_status "$profile" "$integration" "$bindir"
                ok "GitWhisper installed."
                warn "Restart your terminal or run: source $profile"
                ;;
            3)
                setup_project
                ;;
            4)
                if [[ "$installed" == "yes" ]]; then
                    uninstall_all "$profile" "$bindir"
                else
                    err "GitWhisper is not installed in $profile."
                fi
                ;;
            5|q|Q) echo ""; ok "Goodbye."; return 0 ;;
        esac
    done
}

main "$@"
