# GitWhisper Installer - WPF graphical interface
# Run:  powershell -ExecutionPolicy Bypass -File install-gui.ps1
# Requires: Windows, PowerShell 5.1+ (Windows only)

$ErrorActionPreference = "Stop"

[void][System.Reflection.Assembly]::LoadWithPartialName("PresentationFramework")
[void][System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")
[void][System.Reflection.Assembly]::LoadWithPartialName("System.Drawing")

$GW_VERSION   = "0.3.0"
$SCRIPT_DIR   = Split-Path -Parent $MyInvocation.MyCommand.Path
$GW_SCRIPT    = Join-Path $SCRIPT_DIR "gitwhisper.ps1"
$MARKER_START = "# >>> GitWhisper >>>"
$MARKER_END   = "# <<< GitWhisper <<<"

# ---------------------------------------------------------------------------
# Core helpers (mirror install.ps1)
# ---------------------------------------------------------------------------

function Test-Installed {
    param([string]$Path)
    if (-not (Test-Path $Path)) { return $false }
    $content = Get-Content $Path -Raw -ErrorAction SilentlyContinue
    return ($content -and $content.Contains($MARKER_START))
}

function Ensure-Profile {
    param([string]$Path)
    if (-not $Path) { return }
    $dir = Split-Path -Parent $Path
    if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    if (-not (Test-Path $Path)) { New-Item -ItemType File -Path $Path -Force | Out-Null }
}

function Remove-ProfileBlock {
    param([string]$Path)
    if (-not (Test-Path $Path)) { return }
    $content = Get-Content $Path -Raw
    if (-not $content) { return }
    $content = [regex]::Replace($content, "(?s)[\r\n]*" + [regex]::Escape($MARKER_START) + ".*?" + [regex]::Escape($MARKER_END) + "[\r\n]*", "`r`n")
    $content = $content.TrimStart("`r", "`n")
    [System.IO.File]::WriteAllText($Path, $content, [System.Text.Encoding]::UTF8)
}

function Get-BinDirFromProfile {
    param([string]$Path)
    if (-not (Test-Path $Path)) { return "" }
    $content = Get-Content $Path -Raw -ErrorAction SilentlyContinue
    if (-not $content) { return "" }
    $m = [regex]::Match($content, '\$env:Path\s*=\s*"([^"]*?);\$env:Path"')
    if ($m.Success) { return $m.Groups[1].Value }
    return ""
}

function Get-FunctionBlock {
    param([string]$ProfilePath)
    $gw = $GW_SCRIPT.Replace("'", "''")
    @"
$MARKER_START
function gitwhisper { & '$gw' @args }
$MARKER_END
"@
}

function Get-BinBlock {
    param([string]$BinPath)
    @"
$MARKER_START
`$env:Path = "$BinPath;`$env:Path"
$MARKER_END
"@
}

function Install-All {
    param([string]$ProfilePath, [string]$Type, [string]$BinPath)
    Ensure-Profile $ProfilePath
    Remove-ProfileBlock $ProfilePath
    if ($Type -eq "bin") {
        New-Item -ItemType Directory -Path $BinPath -Force | Out-Null
        $cmd = "@echo off`r`npowershell -NoProfile -ExecutionPolicy Bypass -File `"$($GW_SCRIPT.Replace('"', '""'))`" %*`r`n"
        [System.IO.File]::WriteAllText((Join-Path $BinPath "gitwhisper.cmd"), $cmd, [System.Text.Encoding]::ASCII)
        $shim = "#!/usr/bin/env pwsh`r`n# Generated by the GitWhisper installer.`r`n& '$($GW_SCRIPT.Replace("'", "''"))' @args`r`n"
        [System.IO.File]::WriteAllText((Join-Path $BinPath "gitwhisper.ps1"), $shim, [System.Text.Encoding]::UTF8)
        if (-not ($env:Path -split ";" -contains $BinPath)) {
            Add-Content -Path $ProfilePath -Value "`r`n$(Get-BinBlock $BinPath)" -Encoding UTF8
        }
    } else {
        Add-Content -Path $ProfilePath -Value "`r`n$(Get-FunctionBlock $ProfilePath)" -Encoding UTF8
    }
}

function Uninstall-All {
    param([string]$ProfilePath, [string]$BinPath)
    $fromProfile = Get-BinDirFromProfile $ProfilePath
    Remove-ProfileBlock $ProfilePath
    $removed = @()
    foreach ($d in @($BinPath, $fromProfile)) {
        if (-not $d) { continue }
        foreach ($f in @((Join-Path $d "gitwhisper.cmd"), (Join-Path $d "gitwhisper.ps1"))) {
            if (Test-Path $f) { Remove-Item $f -Force; $removed += $f }
        }
    }
    return $removed
}

$gitmoji = @{
    "feat"     = [char]::ConvertFromUtf32(0x2728)
    "fix"      = [char]::ConvertFromUtf32(0x1F41B)
    "docs"     = [char]::ConvertFromUtf32(0x1F4DD)
    "style"    = [char]::ConvertFromUtf32(0x1F484)
    "refactor" = [char]::ConvertFromUtf32(0x267B)
    "perf"     = [char]::ConvertFromUtf32(0x26A1)
    "test"     = [char]::ConvertFromUtf32(0x2705)
    "build"    = [char]::ConvertFromUtf32(0x1F527)
    "ci"       = [char]::ConvertFromUtf32(0x1F477)
    "chore"    = [char]::ConvertFromUtf32(0x1F528)
    "revert"   = [char]::ConvertFromUtf32(0x23EA)
}

# ---------------------------------------------------------------------------
# XAML: main window
# ---------------------------------------------------------------------------

$xaml = @'
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="GitWhisper Installer v0.3.0" Width="920" Height="780"
        WindowStartupLocation="CenterScreen" FontFamily="Segoe UI" FontSize="12.5">
  <Grid Margin="14">
    <Grid.RowDefinitions>
      <RowDefinition Height="Auto"/>
      <RowDefinition Height="Auto"/>
      <RowDefinition Height="Auto"/>
      <RowDefinition Height="*"/>
      <RowDefinition Height="Auto"/>
    </Grid.RowDefinitions>

    <Border Grid.Row="0" Background="#111827" CornerRadius="8" Padding="14,10">
      <StackPanel>
        <TextBlock Text="GitWhisper Installer" FontSize="22" FontWeight="Bold" Foreground="White"/>
        <TextBlock Text="Conventional Commits + gitmoji, automatically." Foreground="#9ca3af"/>
      </StackPanel>
    </Border>

    <GroupBox Grid.Row="1" Header="Install options" Margin="0,12,0,0" Padding="10">
      <Grid>
        <Grid.RowDefinitions>
          <RowDefinition Height="Auto"/>
          <RowDefinition Height="Auto"/>
          <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>
        <Grid.ColumnDefinitions>
          <ColumnDefinition Width="Auto"/>
          <ColumnDefinition Width="*"/>
          <ColumnDefinition Width="Auto"/>
        </Grid.ColumnDefinitions>

        <TextBlock Grid.Row="0" Grid.Column="0" Text="Profile file:" VerticalAlignment="Center" Margin="0,0,8,0"/>
        <TextBox Grid.Row="0" Grid.Column="1" x:Name="txtProfile" Margin="0,0,8,6"/>
        <Button Grid.Row="0" Grid.Column="2" x:Name="btnBrowseProfile" Content="Browse..." Padding="10,3"/>

        <TextBlock Grid.Row="1" Grid.Column="0" Text="Integration:" VerticalAlignment="Center" Margin="0,0,8,0"/>
        <StackPanel Grid.Row="1" Grid.Column="1" Grid.ColumnSpan="2" Orientation="Horizontal" Margin="0,0,0,6">
          <RadioButton x:Name="rdoFunction" GroupName="itype" Content="Function in profile" IsChecked="True" Margin="0,0,18,0"/>
          <RadioButton x:Name="rdoBin" GroupName="itype" Content="Executable in bin directory"/>
        </StackPanel>

        <TextBlock Grid.Row="2" Grid.Column="0" Text="Bin directory:" VerticalAlignment="Center" Margin="0,0,8,0"/>
        <TextBox Grid.Row="2" Grid.Column="1" x:Name="txtBinDir" Margin="0,0,8,0" IsEnabled="False"/>
        <Button Grid.Row="2" Grid.Column="2" x:Name="btnBrowseBin" Content="Browse..." Padding="10,3" IsEnabled="False"/>
      </Grid>
    </GroupBox>

    <StackPanel Grid.Row="2" Orientation="Horizontal" Margin="0,10,0,0">
      <Button x:Name="btnInstall" Content="Install" Padding="20,6" FontWeight="Bold" Margin="0,0,8,0"/>
      <Button x:Name="btnUninstall" Content="Uninstall" Padding="20,6" Margin="0,0,8,0"/>
      <Button x:Name="btnProject" Content="Set up project..." Padding="20,6" Margin="0,0,8,0"/>
      <Button x:Name="btnExit" Content="Exit" Padding="20,6"/>
    </StackPanel>

    <TabControl Grid.Row="3" Margin="0,12,0,0">
      <TabItem Header="Profile preview">
        <Grid Margin="6">
          <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="Auto"/>
          </Grid.RowDefinitions>
          <TextBox x:Name="txtProfilePreview" IsReadOnly="True" FontFamily="Consolas" FontSize="12"
                   VerticalScrollBarVisibility="Auto" HorizontalScrollBarVisibility="Auto"
                   TextWrapping="NoWrap" Background="#0b1220" Foreground="#dbe4f3" Padding="8"/>
          <TextBlock x:Name="txtProfileStatus" Grid.Row="1" Margin="2,6,0,0" Foreground="#6b7280"/>
        </Grid>
      </TabItem>
      <TabItem Header="GitWhisper preview">
        <Grid Margin="6">
          <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="Auto"/>
          </Grid.RowDefinitions>
          <TextBox x:Name="txtGwPreview" IsReadOnly="True" FontFamily="Consolas" FontSize="12"
                   VerticalScrollBarVisibility="Auto" HorizontalScrollBarVisibility="Auto"
                   TextWrapping="NoWrap" Background="#0b1220" Foreground="#dbe4f3" Padding="8"/>
          <StackPanel Grid.Row="1" Orientation="Horizontal" Margin="0,8,0,0">
            <TextBox x:Name="txtDemoDesc" Width="380" Text="adds a login form with validation"/>
            <Button x:Name="btnDemo" Content="Generate example message" Margin="8,0,0,0" Padding="12,4"/>
          </StackPanel>
          <TextBlock x:Name="txtDemoStatus" Grid.Row="2" Margin="2,6,0,0" Foreground="#6b7280"/>
        </Grid>
      </TabItem>
    </TabControl>

    <Border Grid.Row="4" Background="#eef2ff" CornerRadius="6" Padding="10,6" Margin="0,12,0,0">
      <TextBlock x:Name="txtStatus" Text="Ready." Foreground="#3730a3"/>
    </Border>
  </Grid>
</Window>
'@

# ---------------------------------------------------------------------------
# XAML: project setup dialog
# ---------------------------------------------------------------------------

$projXaml = @'
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="Set up project" SizeToContent="WidthAndHeight" ResizeMode="NoResize"
        WindowStartupLocation="CenterOwner" FontFamily="Segoe UI" FontSize="12.5">
  <StackPanel Margin="16" Width="420">
    <TextBlock Text="Install GitWhisper hooks and config for a git project." Foreground="#374151" TextWrapping="Wrap"/>
    <Grid Margin="0,12,0,0">
      <Grid.ColumnDefinitions>
        <ColumnDefinition Width="*"/>
        <ColumnDefinition Width="Auto"/>
      </Grid.ColumnDefinitions>
      <TextBox x:Name="projDir"/>
      <Button x:Name="projBrowse" Grid.Column="1" Content="Browse..." Margin="8,0,0,0" Padding="10,3"/>
    </Grid>
    <CheckBox x:Name="chkEmoji" Content="Include emoji in commit messages" IsChecked="True" Margin="0,12,0,0"/>
    <StackPanel Orientation="Horizontal" Margin="0,8,0,0">
      <TextBlock Text="Default format:" VerticalAlignment="Center" Margin="0,0,8,0"/>
      <ComboBox x:Name="cboDefault" Width="210" SelectedIndex="0">
        <ComboBoxItem Content="1 - simple + emoji"/>
        <ComboBoxItem Content="2 - simple"/>
        <ComboBoxItem Content="3 - detailed + emoji"/>
        <ComboBoxItem Content="4 - detailed"/>
      </ComboBox>
    </StackPanel>
    <CheckBox x:Name="chkPrepare" Content="Enable pre-fill hook (prepare-commit-msg)" IsChecked="True" Margin="0,12,0,0"/>
    <CheckBox x:Name="chkValidate" Content="Enforce Conventional Commits (commit-msg hook)" IsChecked="True" Margin="0,6,0,0"/>
    <StackPanel Orientation="Horizontal" HorizontalAlignment="Right" Margin="0,18,0,0">
      <Button x:Name="projApply" Content="Apply" FontWeight="Bold" Padding="16,5" Margin="0,0,8,0"/>
      <Button x:Name="projCancel" Content="Cancel" Padding="16,5"/>
    </StackPanel>
  </StackPanel>
</Window>
'@

# ---------------------------------------------------------------------------
# Load main window
# ---------------------------------------------------------------------------

$script:projDir = ""
$script:projEmoji = "y"
$script:projDefault = "1"
$script:projPrepare = "y"
$script:projValidate = "y"

$reader = New-Object System.Xml.XmlNodeReader([xml]$xaml)
$window  = [System.Windows.Markup.XamlReader]::Load($reader)

function Ctrl { param([string]$n) $window.FindName($n) }

$txtProfile        = Ctrl "txtProfile"
$txtBinDir         = Ctrl "txtBinDir"
$rdoFunction       = Ctrl "rdoFunction"
$rdoBin            = Ctrl "rdoBin"
$btnBrowseProfile  = Ctrl "btnBrowseProfile"
$btnBrowseBin      = Ctrl "btnBrowseBin"
$btnInstall        = Ctrl "btnInstall"
$btnUninstall      = Ctrl "btnUninstall"
$btnProject        = Ctrl "btnProject"
$btnExit           = Ctrl "btnExit"
$txtProfilePreview = Ctrl "txtProfilePreview"
$txtProfileStatus  = Ctrl "txtProfileStatus"
$txtGwPreview      = Ctrl "txtGwPreview"
$txtDemoDesc       = Ctrl "txtDemoDesc"
$btnDemo           = Ctrl "btnDemo"
$txtDemoStatus     = Ctrl "txtDemoStatus"
$txtStatus         = Ctrl "txtStatus"

function Get-CurrentType {
    if ($rdoBin.IsChecked) { return "bin" }
    return "function"
}

function Set-Status {
    param([string]$Msg, [string]$Color = "#3730a3")
    $txtStatus.Text = $Msg
    $txtStatus.Foreground = [System.Windows.Media.BrushConverter]::new().ConvertFromString($Color)
}

function Update-ProfilePreview {
    $p = $txtProfile.Text.Trim()
    $type = Get-CurrentType
    $b = $txtBinDir.Text.Trim()
    $lines = New-Object System.Collections.Generic.List[string]
    $installed = Test-Installed $p

    if ($type -eq "bin") {
        if (-not $b) { $b = Join-Path $HOME ".local\bin" }
        $lines.Add("Wrapper files to be created:")
        $lines.Add("  $b\gitwhisper.cmd")
        $lines.Add("  $b\gitwhisper.ps1")
        $lines.Add("")
        $lines.Add("Block to be appended to the profile:")
        $lines.Add("")
        $lines.Add((Get-BinBlock $b))
        $binInstalled = (Test-Path "$b\gitwhisper.cmd") -or (Test-Path "$b\gitwhisper.ps1")
        $statusBits = @()
        if ($installed) { $statusBits += "profile has a GitWhisper block" }
        if ($binInstalled) { $statusBits += "wrapper files already exist" }
        if ($statusBits.Count -eq 0) {
            $txtProfileStatus.Text = "Nothing installed yet - clicking Install will create these files."
        } else {
            $txtProfileStatus.Text = ($statusBits -join "; ") + " - Install will replace them."
        }
    } else {
        $lines.Add("Function to be appended to the profile:")
        $lines.Add("")
        $lines.Add((Get-FunctionBlock $p))
        if ($installed) {
            $txtProfileStatus.Text = "A GitWhisper block already exists in this profile - Install will replace it."
        } else {
            $txtProfileStatus.Text = "Nothing installed yet - clicking Install will append this function."
        }
    }

    if (-not $p) {
        $txtProfilePreview.Text = "Enter a profile file path to see the preview."
        $txtProfileStatus.Text = ""
        return
    }
    $txtProfilePreview.Text = ($lines -join "`r`n")
}

function Get-CheatSheet {
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("Conventional Commit types + gitmoji")
    [void]$sb.AppendLine("====================================")
    foreach ($type in @("feat", "fix", "docs", "test", "style", "refactor", "perf", "build", "ci", "chore", "revert")) {
        [void]$sb.AppendLine(("{0,-9} {1}" -f $gitmoji[$type], $type))
    }
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("Generated messages look like:")
    [void]$sb.AppendLine("  " + $gitmoji["feat"] + " feat(auth): adds Login component")
    [void]$sb.AppendLine("  " + $gitmoji["fix"] + " fix(api): adds error handling in user.js")
    [void]$sb.AppendLine("  " + $gitmoji["docs"] + " docs: adds README.md")
    [void]$sb.AppendLine("  " + $gitmoji["test"] + " test(payments): covers refund flow")
    [void]$sb.AppendLine("  " + $gitmoji["perf"] + " perf(search): adds caching")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("Type is inferred from your diff, with a fallback to")
    [void]$sb.AppendLine("the current branch name when it starts with feat/, fix/,")
    [void]$sb.AppendLine("docs/, test/, chore/, refactor/, perf/, style/, ci/, build/.")
    return $sb.ToString()
}

function Update-GwPreview {
    $txtGwPreview.Text = Get-CheatSheet
}

function Generate-DemoMessage {
    param([string]$Description)
    if (-not $Description) { $Description = "adds a small feature" }
    $tmp = Join-Path ([IO.Path]::GetTempPath()) ("gw-demo-" + [guid]::NewGuid().ToString("N"))
    try {
        New-Item -ItemType Directory -Path $tmp | Out-Null
        & git -C $tmp init -q
        $tree = (& git -C $tmp write-tree).Trim()
        $commit = "baseline" | & git -C $tmp commit-tree $tree
        & git -C $tmp update-ref HEAD $commit
        & git -C $tmp reset -q
        $word = ($Description -split "\s+" | Where-Object { $_ } | Select-Object -Last 1)
        $content = @"
const $word = { ok: true };
export default $word;
"@
        [System.IO.File]::WriteAllText((Join-Path $tmp "demo.js"), $content, [System.Text.Encoding]::UTF8)
        & git -C $tmp add demo.js
        Push-Location $tmp
        try { $out = & powershell -NoProfile -ExecutionPolicy Bypass -File $GW_SCRIPT suggest 2>&1 | Out-String }
        finally { Pop-Location }
        $out = $out.Trim()
        if (-not $out) { $out = "(no suggestion generated - the temp repo produced no diff)" }
        return $out
    }
    catch {
        return "Could not generate a live example: $($_.Exception.Message)"
    }
    finally {
        if (Test-Path $tmp) { Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue }
    }
}

function Show-ProjectDialog {
    $preader = New-Object System.Xml.XmlNodeReader([xml]$projXaml)
    $projWin = [System.Windows.Markup.XamlReader]::Load($preader)
    $projWin.Owner = $window

    $projDirBox   = $projWin.FindName("projDir")
    $projBrowse   = $projWin.FindName("projBrowse")
    $chkEmoji     = $projWin.FindName("chkEmoji")
    $cboDefault   = $projWin.FindName("cboDefault")
    $chkPrepare   = $projWin.FindName("chkPrepare")
    $chkValidate  = $projWin.FindName("chkValidate")
    $projApply    = $projWin.FindName("projApply")
    $projCancel   = $projWin.FindName("projCancel")

    $script:projDir = (Get-Location).Path
    $projDirBox.Text = $script:projDir

    $projBrowse.Add_Click({
        $dlg = New-Object System.Windows.Forms.FolderBrowserDialog
        $dlg.Description = "Select a git project directory"
        if ($projDirBox.Text) { $dlg.SelectedPath = $projDirBox.Text }
        if ($dlg.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) {
            $projDirBox.Text = $dlg.SelectedPath
        }
    })

    $projCancel.Add_Click({ $projWin.DialogResult = $false; $projWin.Close() })
    $projApply.Add_Click({
        $d = $projDirBox.Text.Trim()
        if (-not $d) {
            [System.Windows.MessageBox]::Show("Choose a project directory.", "GitWhisper", "OK", "Warning") | Out-Null
            return
        }
        $script:projDir = $d
        $script:projEmoji    = if ($chkEmoji.IsChecked) { "y" } else { "n" }
        $script:projDefault  = [string]($cboDefault.SelectedIndex + 1)
        $script:projPrepare  = if ($chkPrepare.IsChecked) { "y" } else { "n" }
        $script:projValidate = if ($chkValidate.IsChecked) { "y" } else { "n" }
        $projWin.DialogResult = $true
        $projWin.Close()
    })

    return $projWin.ShowDialog()
}

function Do-ProjectSetup {
    if (-not (Test-Path $GW_SCRIPT)) {
        Set-Status "gitwhisper.ps1 not found next to this installer." "#b91c1c"
        return
    }
    if ((Show-ProjectDialog) -ne $true) { return }
    $dir = $script:projDir
    try {
        if (-not (Test-Path "$dir\.git")) {
            Set-Status "No .git directory found in $dir." "#b45309"
            return
        }
        $config = @"

# GitWhisper configuration
# Created by the GitWhisper installer.

[general]
emoji = $($script:projEmoji)
default = $($script:projDefault)

[hooks]
prepare = $($script:projPrepare)
validate = $($script:projValidate)
"@
        Set-Content -Path "$dir\.gitwhisperconfig" -Value $config.TrimStart() -Encoding UTF8
        Push-Location $dir
        try { & powershell -NoProfile -ExecutionPolicy Bypass -File $GW_SCRIPT init | Out-Null } finally { Pop-Location }
        Set-Status "Project $dir is ready (config + hooks installed)." "#15803d"
    }
    catch {
        Set-Status "Project setup failed: $($_.Exception.Message)" "#b91c1c"
    }
}

function Do-Install {
    $p = $txtProfile.Text.Trim()
    if (-not $p) {
        Set-Status "Enter a profile file path first." "#b91c1c"
        return
    }
    if (-not (Test-Path $GW_SCRIPT)) {
        Set-Status "gitwhisper.ps1 not found next to this installer." "#b91c1c"
        return
    }
    try {
        Install-All $p (Get-CurrentType) $txtBinDir.Text.Trim()
        Update-ProfilePreview
        Set-Status "Installed. Restart your terminal or run: . $PROFILE" "#15803d"
    }
    catch {
        Set-Status "Install failed: $($_.Exception.Message)" "#b91c1c"
    }
}

function Do-Uninstall {
    $p = $txtProfile.Text.Trim()
    if (-not $p) {
        Set-Status "Enter a profile file path first." "#b91c1c"
        return
    }
    if (-not (Test-Installed $p)) {
        Set-Status "GitWhisper is not installed in $p." "#b45309"
        return
    }
    try {
        $removed = Uninstall-All $p $txtBinDir.Text.Trim()
        Update-ProfilePreview
        $extra = if ($removed.Count -gt 0) { " Removed wrapper files." } else { "" }
        Set-Status "Uninstalled.$extra Restart your terminal or run: . $PROFILE" "#15803d"
    }
    catch {
        Set-Status "Uninstall failed: $($_.Exception.Message)" "#b91c1c"
    }
}

# ---------------------------------------------------------------------------
# Event wiring
# ---------------------------------------------------------------------------

$btnBrowseProfile.Add_Click({
    $dlg = New-Object Microsoft.Win32.SaveFileDialog
    $dlg.Title = "Select the shell profile file"
    $dlg.FileName = Split-Path -Leaf $PROFILE
    $dlg.Filter = "Profile files (*.ps1;*.bashrc;*.zshrc)|*.ps1;*.bashrc;*.zshrc;*.profile|All files (*.*)|*.*"
    if ($dlg.ShowDialog($window) -eq $true) { $txtProfile.Text = $dlg.FileName }
})

$btnBrowseBin.Add_Click({
    $dlg = New-Object System.Windows.Forms.FolderBrowserDialog
    $dlg.Description = "Select the bin directory"
    if ($txtBinDir.Text) { $dlg.SelectedPath = $txtBinDir.Text }
    if ($dlg.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) { $txtBinDir.Text = $dlg.SelectedPath }
})

$rdoFunction.Add_Checked({ $txtBinDir.IsEnabled = $false; $btnBrowseBin.IsEnabled = $false; Update-ProfilePreview })
$rdoBin.Add_Checked({ $txtBinDir.IsEnabled = $true; $btnBrowseBin.IsEnabled = $true; Update-ProfilePreview })

$txtProfile.Add_TextChanged({ Update-ProfilePreview })
$txtBinDir.Add_TextChanged({ Update-ProfilePreview })

$btnInstall.Add_Click({ Do-Install })
$btnUninstall.Add_Click({ Do-Uninstall })
$btnProject.Add_Click({ Do-ProjectSetup })
$btnExit.Add_Click({ $window.Close() })

$btnDemo.Add_Click({
    $txtDemoStatus.Text = "Generating a live suggestion from a temporary git repository..."
    $window.Dispatcher.Invoke([Action]{}, [System.Windows.Threading.DispatcherPriority]::Background)
    $out = Generate-DemoMessage $txtDemoDesc.Text
    $txtGwPreview.Text = $out
    $txtDemoStatus.Text = "Live suggestion from gitwhisper (temp repo)."
})

# ---------------------------------------------------------------------------
# Init + show
# ---------------------------------------------------------------------------

$txtProfile.Text = $PROFILE
$txtBinDir.Text = Join-Path $HOME ".local\bin"
Update-GwPreview
Update-ProfilePreview

[void]$window.ShowDialog()
