# LLM integration (OpenAI-compatible chat completions, e.g. Ollama).
# Every call is best-effort: any error/timeout falls back to the heuristic
# message generated by message.compute_message().

import json
import urllib.error
import urllib.request

import message as message_mod


def _request(cfg, path, payload=None, method="GET"):
    url = cfg.llm_url.rstrip("/") + path
    headers = {"Content-Type": "application/json"}
    if cfg.llm_api_key:
        headers["Authorization"] = "Bearer %s" % cfg.llm_api_key
    data = json.dumps(payload).encode("utf-8") if payload is not None else None
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    with urllib.request.urlopen(req, timeout=cfg.llm_timeout) as resp:
        return json.loads(resp.read().decode("utf-8"))


def ollama_reachable(base_url="http://localhost:11434"):
    """Probe the Ollama server's /api/tags endpoint (used by `init`)."""
    try:
        req = urllib.request.Request(base_url.rstrip("/") + "/api/tags", method="GET")
        with urllib.request.urlopen(req, timeout=3) as resp:
            return resp.status == 200
    except Exception:
        return False


def chat(cfg, messages):
    payload = {
        "model": cfg.llm_model,
        "messages": messages,
        "temperature": 0.3,
        "max_tokens": cfg.llm_max_tokens,
        "stream": False,
    }
    body = _request(cfg, "/chat/completions", payload, method="POST")
    return body["choices"][0]["message"]["content"]


def _build_context(added, modified, deleted, diff_content):
    files = []
    for f in added:
        files.append("A  %s" % f)
    for f in modified:
        files.append("M  %s" % f)
    for f in deleted:
        files.append("D  %s" % f)
    diff = diff_content[:4000]
    return files, diff


def suggest(cfg, added, modified, deleted, diff_content, m):
    """Return (title, body) generated by the LLM, or (None, None) on failure."""
    if not cfg.llm_enabled:
        return None, None
    try:
        files, diff = _build_context(added, modified, deleted, diff_content)
        heuristic_title = m["title"] if m else ""
        if cfg.llm_mode == "full":
            prompt = (
                "You write Git commit messages following Conventional Commits.\n\n"
                "Files changed:\n%s\n\n"
                "Git diff (truncated):\n%s\n\n"
                "Heuristic suggestion (for reference only):\n%s\n\n"
                "Write ONLY the final commit message: a subject line, a blank line, "
                "and a short bullet list of the main changes. No commentary, no quotes."
                % ("\n".join(files), diff, heuristic_title)
            )
            content = chat(cfg, [
                {"role": "system", "content": "You are an expert at writing concise Conventional Commits messages."},
                {"role": "user", "content": prompt},
            ])
            lines = [ln for ln in content.strip().split("\n")]
            title = ""
            for ln in lines:
                if ln.strip():
                    title = ln.strip()
                    break
            body_lines = []
            started = False
            for ln in lines:
                if ln.strip() == title:
                    started = True
                    continue
                if started:
                    body_lines.append(ln)
            return title, "\n".join(body_lines).strip("\n")
        else:
            prompt = (
                "You write Git commit subject lines.\n\n"
                "Files changed:\n%s\n\n"
                "Git diff (truncated):\n%s\n\n"
                "Heuristic subject: %s\n\n"
                "Write ONLY the description text that goes after "
                "'<type>(<scope>): '. Imperative mood, under 50 characters. "
                "No type, no scope, no emoji, no quotes."
                % ("\n".join(files), diff, heuristic_title)
            )
            content = chat(cfg, [
                {"role": "system", "content": "You are an expert at writing concise Git commit subject lines."},
                {"role": "user", "content": prompt},
            ])
            desc = content.strip().split("\n")[0].strip().strip("\"'")
            if not desc:
                return None, None
            emoji = m["emoji"] if (m and m["emoji_on"]) else ""
            if m and m["scope"]:
                title = "%s %s(%s): %s" % (emoji, m["type"], m["scope"], desc) if emoji else "%s(%s): %s" % (m["type"], m["scope"], desc)
            else:
                title = "%s %s: %s" % (emoji, m["type"], desc) if emoji else "%s: %s" % (m["type"], desc)
            body = message_mod.build_body(added, modified, deleted, desc, "")
            return title, body
    except Exception:
        return None, None
