import os

import git_helpers as git
import llm
from config import load_config
from ui import out, prompt

CONFIG_TEMPLATE = """# GitWhisper configuration
# Created by `gitwhisper init`. Re-run `gitwhisper init` to update hooks after edits.

[general]
# include emoji in generated commit messages (true/false)
emoji = true

# suggestion pre-filled by the hook: 1=simple+emoji, 2=simple, 3=detailed+emoji, 4=detailed
default = 1

# maintainers excluded from the "community contributors" section of the changelog
core_maintainers =

# force every commit to use this scope, e.g. force = core
#scope =

[types]
# customize an existing type's emoji and changelog section title:
#   <type> = <emoji>|<Section Title>
# feat = <emoji>|Features
# fix  = <emoji>|Bug Fixes

# add a brand-new type (it will also be accepted by the commit-msg hook):
# security = <emoji>|Security

# reorder changelog/PR sections with <type>.order = <number> (default 999):
# fix.order = 1

[scope]
# map a directory (prefix match) to a scope:
# api = api
# core = core
#   When a commit touches several mapped paths, the first match wins.

[hooks]
# pre-fill the commit message on `git commit` (true/false)
prepare = true

# reject commits that do not follow Conventional Commits (true/false)
validate = true

[llm]
# use a local LLM (OpenAI-compatible, e.g. Ollama) to write commit descriptions.
# init enables it automatically when an Ollama server is reachable.
enabled = __LLM_ENABLED__

# base URL of the OpenAI-compatible endpoint (Ollama exposes /v1)
url = http://localhost:11434/v1

# model to use (run `ollama list` to see what is installed)
model = llama3.2

# description = LLM writes the subject only; full = LLM writes the whole message
mode = description

# seconds to wait for the LLM before falling back to the built-in heuristics
timeout = 30

# maximum number of tokens in the LLM response
max_tokens = 150

# language of the LLM output, e.g. pt-BR, en, es (empty = model default)
language = __LLM_LANGUAGE__

# API key, only needed for remote providers (leave empty for Ollama)
#api_key =
"""

PREPARE_HOOK_TEMPLATE = """#!/bin/sh
# Generated by GitWhisper init. Re-run `gitwhisper init` to update.
GW_CMD="__GW_CMD__"

MSG_FILE="$1"
SOURCE="$2"

# only pre-fill plain commits (skip -m, --amend, merge, template, etc.)
case "$SOURCE" in
    message|template|merge|squash|commit) exit 0 ;;
esac

# do nothing when there are no staged changes
if ! git diff --cached --quiet 2>/dev/null; then
    SUGGEST=$(eval "$GW_CMD suggest < /dev/null" 2>/dev/null)
    if [ -n "$SUGGEST" ]; then
        # only pre-fill when the message file has no real content yet
        REAL=$(grep -v '^#' "$MSG_FILE" | grep -v '^[[:space:]]*$' | head -1)
        if [ -z "$REAL" ]; then
            printf '%s\\n' "$SUGGEST" > "$MSG_FILE"
        fi
    fi
fi

exit 0
"""

COMMIT_MSG_HOOK = """#!/bin/sh
# Generated by GitWhisper init. Re-run `gitwhisper init` to update.
MSG_FILE="$1"

# default types + any extra types declared in the project's [types] section
TYPES="feat fix docs style refactor perf test build ci chore revert db"
if [ -f .gitwhisperconfig ]; then
    CFG_TYPES=$(awk '/^\\[types\\]/{t=1;next} /^\\[/{t=0} t && /^[[:space:]]*[A-Za-z0-9_-]+[[:space:]]*=/{split($0,a,"="); gsub(/[[:space:]]/,"",a[1]); printf "%s ", a[1]}' .gitwhisperconfig 2>/dev/null)
    [ -n "$CFG_TYPES" ] && TYPES="$TYPES $CFG_TYPES"
fi
TYPES_ALT=$(echo "$TYPES" | tr ' ' '|')

FIRST_LINE=""
while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
        \\#*) continue ;;
        "") continue ;;
    esac
    FIRST_LINE="$line"
    break
done < "$MSG_FILE"

if ! echo "$FIRST_LINE" | grep -qE "^[^[:alnum:]]*(${TYPES_ALT})(\\([^)]*\\))?(!)?: .+"; then
    echo ""
    echo "GitWhisper: commit message does not follow Conventional Commits."
    echo ""
    echo "  Expected: <type>(<scope>): <description>"
    echo "  Example:  feat(api): add login endpoint"
    echo ""
    echo "  Run 'gitwhisper' to generate a message, or edit the subject line."
    echo ""
    exit 1
fi

exit 0
"""


def _gw_command(root):
    sh = os.path.join(root, "gitwhisper.sh")
    if os.path.isfile(sh):
        return "bash '%s'" % sh.replace("\\", "/")
    ps1 = os.path.join(root, "gitwhisper.ps1")
    if os.path.isfile(ps1):
        return "powershell.exe -NoProfile -ExecutionPolicy Bypass -File '%s'" % ps1.replace("\\", "/")
    return "gitwhisper"


def _write_hook(path, content, force):
    leaf = os.path.basename(path)
    if os.path.isfile(path):
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as fh:
                existing = fh.read()
        except OSError:
            existing = ""
        if existing and "GitWhisper" not in existing:
            if not force:
                out("")
                answer = prompt("  %s exists and is not from GitWhisper. Back up and overwrite? (y/n)" % leaf)
                if answer.lower() != "y":
                    out("  Skipping %s." % leaf)
                    return
            with open(path + ".bak", "w", encoding="utf-8") as fh:
                fh.write(existing)
            out("  Backed up existing hook to %s.bak" % path)
    with open(path, "w", encoding="ascii", newline="") as fh:
        fh.write(content)
    out("  Installed %s" % leaf)


def run(cfg, args, dry_run=False):
    force = "--force" in args or "-Force" in args

    out("")
    out("=== GitWhisper init ===")
    out("")

    config_path = ".gitwhisperconfig"
    if os.path.isfile(config_path):
        if force:
            out("  .gitwhisperconfig already exists. Recreating.")
            _new_config_file()
        else:
            out("  .gitwhisperconfig already exists. Keeping it.")
    else:
        _new_config_file()

    hooks_dir = os.path.join(".git", "hooks")
    if not os.path.isdir(hooks_dir):
        out("")
        out("  Error: could not find %s." % hooks_dir)
        return 1

    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    gw_cmd = _gw_command(root)

    loaded = load_config(config_path)

    prepare_path = os.path.join(hooks_dir, "prepare-commit-msg")
    commit_msg_path = os.path.join(hooks_dir, "commit-msg")

    if not loaded.hooks_prepare:
        if os.path.exists(prepare_path):
            os.remove(prepare_path)
        out("  prepare-commit-msg disabled in config. Removed.")
    else:
        content = PREPARE_HOOK_TEMPLATE.replace("__GW_CMD__", gw_cmd)
        _write_hook(prepare_path, content, force)

    if not loaded.hooks_validate:
        if os.path.exists(commit_msg_path):
            os.remove(commit_msg_path)
        out("  commit-msg disabled in config. Removed.")
    else:
        _write_hook(commit_msg_path, COMMIT_MSG_HOOK, force)

    out("")
    out("  Done! GitWhisper hooks installed.")
    out("  Next 'git commit' will pre-fill a suggested message.")
    out("  Config file: .gitwhisperconfig")
    out("")
    return 0


def _new_config_file():
    if llm.ollama_reachable("http://localhost:11434"):
        enabled = "true"
    else:
        enabled = "false"
    content = CONFIG_TEMPLATE.replace("__LLM_ENABLED__", enabled)
    content = content.replace("__LLM_LANGUAGE__", "en")
    with open(".gitwhisperconfig", "w", encoding="utf-8", newline="") as fh:
        fh.write(content)
    out("  Created .gitwhisperconfig")
